language: java

# Before update, we use java16 by sdk
before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 16.0.2-open
  - sdk use java 16.0.2-open

# jdk:
#  - openjdk16

branches:
  only:
    - main

# Travis CI Server's Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp api/build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/apply-home.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: apply-home-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true
    on:
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: apply-home-build
    key: apply-home.zip
    bundle_type: zip
    application: apply-home
    deployment_group: apply-home-group
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      branch: main

after_success:
  - ./gradlew jacocoTestReport coveralls

# CI 실행 완료시, 이메일 알람
notifications:
  email:
    recipients:
      - pipiolo1024@gmail.com