language: java
jdk:
  - openjdk16

branches:
  only:
    - main

# Travis CI Server's Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r apply-home
  - mkdir -p deploy
  - mv apply-home.zip deploy/apply-home.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: apply-home-build
    region: ap-northeast-2
    cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

# CI 실행 완료시, 이메일 알람
notifications:
  email:
    recipients:
      - copy.h13@gmail.com
